"""
Seed generation -- the stage between "a player chose options" and "there is a room".

WHY THIS EXISTS. Peliarch already hosts a room from a `.archipelago` someone generated elsewhere;
the dashboard says so ("Generated by the AP client -- hosting only"). That leaves the player doing
the hardest part off-platform: install Python, install Archipelago, install the apworld, run
Generate.py, then come back and upload. This module closes the loop, so a yaml -- from the Elden
Ring options wizard, or pasted by hand -- becomes a running room in one request.

It is deliberately a THIN wrapper around stock `Generate.py` rather than an import of AP's
generation internals. Three reasons, in order of how much they cost to get wrong:

  1. `Generate.py` is the interface upstream supports and tests. Calling into `Main.main()` directly
     couples us to internals that move between point releases, and we track a moving upstream.
  2. A subprocess can be BOUNDED. In-process generation cannot be: there is no way to cap the RSS
     or CPU of a fill running inside the Flask worker, and no way to abandon it once it starts.
  3. A crash in generation must not take the room host down with it. Rooms that are already running
     are the product; a bad yaml must be able to fail without touching them.

🛑 THIS IS THE UNTRUSTED-INPUT SURFACE OF THE WHOLE SITE. Everything else on peliarch accepts a
multidata and validates it structurally without ever unpickling it (`validate_archipelago_upload`).
This endpoint, by contrast, hands attacker-controlled text to a program that will happily follow it.
An AP yaml is not data -- it carries weights, triggers and plando directives that steer allocation
and runtime. So every limit below is load-bearing, not decoration:

  * WALL TIMEOUT -- a fill can be made to run effectively forever by a hostile weight set. The
    process is killed by PROCESS GROUP (`os.setsid` + `killpg`), because Generate spawns children
    and killing only the parent leaves them running and holding the port range's box.
  * RLIMIT_AS -- an address-space cap the child cannot raise. Chosen against a measured baseline: a
    real solo Elden Ring seed peaks at ~170 MB RSS, so the default 2 GB is roughly a 12x headroom
    for multiworld and still far from what an allocation bomb wants.
  * RLIMIT_CPU -- catches a spin that produces no output and would otherwise sit under the wall
    clock doing nothing but burning a core.
  * PLANDO OFF BY DEFAULT (`--plando ""`). AP already has this lever; the public endpoint should
    use it. Plando is the part of the yaml that most directly places items and touches paths.
  * A SIZE CAP and a YAML PARSE before we spend a process at all -- rejecting garbage should not
    cost a fork.

None of this makes generation safe to run as root, or without a per-IP rate limit in front. It
makes it survivable.
"""
from __future__ import annotations

import glob
import logging
import os
import resource
import signal
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from typing import List, Optional, Sequence, Tuple

logger = logging.getLogger(__name__)

# Defaults. Every one is overridable per call so the tests can drive them to their edges.
DEFAULT_TIMEOUT_SECONDS = 180
DEFAULT_MAX_ADDRESS_SPACE_MB = 2048
DEFAULT_MAX_CPU_SECONDS = 240
DEFAULT_YAML_MAX_BYTES = 256 * 1024
DEFAULT_MAX_PLAYERS = 32

# AP's own knob for how much of a yaml's plando section is honoured. Empty = none of it.
DEFAULT_PLANDO = ""


class GenerationError(Exception):
    """Generation failed. `detail` is a trimmed tail of the child's output, safe to show a user."""

    def __init__(self, message: str, detail: str = "", timed_out: bool = False):
        super().__init__(message)
        self.detail = detail
        self.timed_out = timed_out


@dataclass
class GeneratedSeed:
    data: bytes
    filename: str
    stdout_tail: str


def validate_yamls(yamls: Sequence[bytes],
                   max_bytes: int = DEFAULT_YAML_MAX_BYTES,
                   max_players: int = DEFAULT_MAX_PLAYERS) -> None:
    """Cheap rejections, before a process is spent. Raises ValueError with a user-facing message.

    Note what this does NOT try to be: a safety boundary. A yaml that parses and names a real game
    can still drive a hostile fill -- that is what the process limits are for. This only stops the
    obvious waste.
    """
    if not yamls:
        raise ValueError("No yaml supplied")
    if len(yamls) > max_players:
        raise ValueError(f"Too many player files: {len(yamls)} exceeds the cap of {max_players}")

    total = sum(len(y) for y in yamls)
    if total > max_bytes:
        raise ValueError(f"Player files too large: {total // 1024} KB exceeds the cap of "
                         f"{max_bytes // 1024} KB")

    try:
        import yaml as _yaml
    except ImportError:  # pyyaml is an AP dependency; if it is missing, let Generate say so
        return

    for i, raw in enumerate(yamls, 1):
        try:
            docs = [d for d in _yaml.safe_load_all(raw) if d is not None]
        except Exception as e:
            raise ValueError(f"Player file {i} is not valid YAML: {e}")
        if not docs:
            raise ValueError(f"Player file {i} is empty")
        for doc in docs:
            if not isinstance(doc, dict):
                raise ValueError(f"Player file {i} must be a mapping (name/game/...)")
            if "game" not in doc:
                raise ValueError(f"Player file {i} has no `game:` key")
            if "name" not in doc:
                raise ValueError(f"Player file {i} has no `name:` key")


def _limits(max_address_space_mb: int, max_cpu_seconds: int):
    """preexec_fn for the child: its own process group, then caps it cannot raise.

    The new session is the important half. Generate spawns children, and a timeout that kills only
    the parent leaves those children running on the box with nothing tracking them.
    """
    def _apply():
        os.setsid()
        if max_address_space_mb:
            limit = max_address_space_mb * 1024 * 1024
            resource.setrlimit(resource.RLIMIT_AS, (limit, limit))
        if max_cpu_seconds:
            resource.setrlimit(resource.RLIMIT_CPU, (max_cpu_seconds, max_cpu_seconds))
        resource.setrlimit(resource.RLIMIT_CORE, (0, 0))
    return _apply


def generate(yamls: Sequence[bytes],
             ap_root: str,
             *,
             seed: Optional[int] = None,
             spoiler: int = 1,
             plando: str = DEFAULT_PLANDO,
             timeout: int = DEFAULT_TIMEOUT_SECONDS,
             max_address_space_mb: int = DEFAULT_MAX_ADDRESS_SPACE_MB,
             max_cpu_seconds: int = DEFAULT_MAX_CPU_SECONDS,
             python_executable: Optional[str] = None) -> GeneratedSeed:
    """Run stock `Generate.py` over `yamls` and return the output zip's bytes.

    `ap_root` is the Archipelago checkout to generate with -- the pinned deploy tree, with whatever
    apworlds are installed into it. Nothing here knows about Elden Ring specifically; the wizard is
    just the first caller.
    """
    validate_yamls(yamls)

    generate_py = os.path.join(ap_root, "Generate.py")
    if not os.path.isfile(generate_py):
        raise GenerationError(f"No Generate.py in {ap_root!r} -- is the AP tree deployed?")

    with tempfile.TemporaryDirectory(prefix="peliarch-gen-") as work:
        players = os.path.join(work, "players")
        out = os.path.join(work, "out")
        home = os.path.join(work, "home")
        for d in (players, out, home):
            os.makedirs(d, exist_ok=True)

        for i, raw in enumerate(yamls, 1):
            with open(os.path.join(players, f"player{i}.yaml"), "wb") as f:
                f.write(raw)

        cmd = [python_executable or sys.executable, generate_py,
               "--player_files_path", players,
               "--outputpath", out,
               "--spoiler", str(spoiler),
               "--plando", plando]
        if seed is not None:
            cmd += ["--seed", str(int(seed))]

        env = dict(os.environ)
        env.update({
            "AP_NONINTERACTIVE": "1",       # never block on a prompt in a web request
            "SKIP_REQUIREMENTS_UPDATE": "1",  # do not let a generation try to pip-install
            "HOME": home,                   # AP writes caches under HOME; keep it in the temp dir
            "TMPDIR": work,
            "PYTHONDONTWRITEBYTECODE": "1",
        })

        proc = subprocess.Popen(
            cmd, cwd=ap_root, env=env,
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            preexec_fn=_limits(max_address_space_mb, max_cpu_seconds),
        )
        try:
            output, _ = proc.communicate(timeout=timeout)
        except subprocess.TimeoutExpired:
            _killpg(proc)
            output, _ = proc.communicate()
            raise GenerationError(
                f"Generation exceeded the {timeout}s limit and was stopped.",
                detail=_tail(output), timed_out=True)

        text = _tail(output)
        if proc.returncode != 0:
            raise GenerationError("Generation failed.", detail=text)

        zips = sorted(glob.glob(os.path.join(out, "AP_*.zip")))
        if not zips:
            # Exit 0 with no artifact is a real state (and has been a real bug upstream), so it gets
            # its own message rather than an IndexError.
            raise GenerationError("Generation reported success but produced no seed file.",
                                  detail=text)
        path = zips[-1]
        with open(path, "rb") as f:
            data = f.read()
        return GeneratedSeed(data=data, filename=os.path.basename(path), stdout_tail=text)


def _killpg(proc) -> None:
    """SIGTERM the child's whole process group, then SIGKILL what is left."""
    for sig in (signal.SIGTERM, signal.SIGKILL):
        try:
            os.killpg(os.getpgid(proc.pid), sig)
        except (ProcessLookupError, PermissionError):
            return
        try:
            proc.wait(timeout=5)
            return
        except subprocess.TimeoutExpired:
            continue


def _tail(output: Optional[bytes], limit: int = 4000) -> str:
    if not output:
        return ""
    text = output.decode("utf-8", "replace").strip()
    return text if len(text) <= limit else "..." + text[-limit:]
